package com.sentinelguard.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sentinelguard.data.preferences.SecurePreferencesManager
import com.sentinelguard.email.EmailService
import com.sentinelguard.report.ForensicReportGenerator
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.io.File
import java.text.SimpleDateFormat
import java.util.*
import javax.inject.Inject

enum class ExportMethod {
    SAVE_TO_DEVICE,
    SEND_EMAIL
}

data class ForensicReportUiState(
    val isGenerating: Boolean = false,
    val generatedFile: File? = null,
    val error: String? = null,
    val emailSent: Boolean = false,
    val emailConfigured: Boolean = false,
    val userEmail: String = ""  // Pre-populated from account settings
)

@HiltViewModel
class ForensicReportViewModel @Inject constructor(
    private val reportGenerator: ForensicReportGenerator,
    private val emailService: EmailService,
    private val securePreferencesManager: SecurePreferencesManager
) : ViewModel() {
    
    private val _uiState = MutableStateFlow(ForensicReportUiState())
    val uiState: StateFlow<ForensicReportUiState> = _uiState.asStateFlow()
    
    init {
        // Check if email is configured and get user's email
        val userEmail = securePreferencesManager.alertRecipient ?: ""
        _uiState.update { 
            it.copy(
                emailConfigured = emailService.hasCredentials(),
                userEmail = userEmail
            ) 
        }
    }
    
    fun generateReport(fileName: String, watermarkOpacity: Float) {
        viewModelScope.launch {
            _uiState.update { it.copy(isGenerating = true, error = null) }
            
            val result = reportGenerator.generateReport(fileName, watermarkOpacity)
            
            result.fold(
                onSuccess = { file ->
                    _uiState.update { 
                        it.copy(isGenerating = false, generatedFile = file) 
                    }
                },
                onFailure = { exception ->
                    _uiState.update { 
                        it.copy(
                            isGenerating = false, 
                            error = "Failed to generate report: ${exception.message}"
                        ) 
                    }
                }
            )
        }
    }
    
    /**
     * Generates report and sends directly to configured email
     */
    fun generateAndEmailReport(fileName: String, watermarkOpacity: Float, recipientEmail: String) {
        viewModelScope.launch {
            _uiState.update { it.copy(isGenerating = true, error = null, emailSent = false) }
            
            // First generate the report
            val reportResult = reportGenerator.generateReport(fileName, watermarkOpacity)
            
            reportResult.fold(
                onSuccess = { file ->
                    // Now send via email
                    val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault())
                    val timestamp = dateFormat.format(Date())
                    
                    val subject = "🔐 SentinelGuard Forensic Report - $timestamp"
                    val body = """
                        |SentinelGuard Forensic Security Report
                        |======================================
                        |
                        |Report Generated: $timestamp
                        |File Name: ${file.name}
                        |
                        |This report contains comprehensive security assessment data including:
                        |• Device information and security status
                        |• Network and cell tower connection history
                        |• Security incidents and alerts
                        |• Behavioral analysis results
                        |• App usage analytics
                        |
                        |⚠️ This report contains sensitive security information.
                        |Please store securely and delete after review if not needed.
                        |
                        |---
                        |Generated by SentinelGuard
                        |Privacy-First Device Security
                    """.trimMargin()
                    
                    val emailSuccess = emailService.sendEmailWithAttachment(
                        recipientEmail = recipientEmail,
                        subject = subject,
                        body = body,
                        attachmentFile = file,
                        attachmentName = "${fileName}.pdf"
                    )
                    
                    // Clean up temp file
                    file.delete()
                    
                    if (emailSuccess) {
                        _uiState.update { 
                            it.copy(isGenerating = false, emailSent = true) 
                        }
                    } else {
                        _uiState.update { 
                            it.copy(
                                isGenerating = false, 
                                error = "Failed to send email. Check your email settings."
                            ) 
                        }
                    }
                },
                onFailure = { exception ->
                    _uiState.update { 
                        it.copy(
                            isGenerating = false, 
                            error = "Failed to generate report: ${exception.message}"
                        ) 
                    }
                }
            )
        }
    }
    
    fun clearGeneratedFile() {
        _uiState.update { it.copy(generatedFile = null) }
    }
    
    fun clearEmailSent() {
        _uiState.update { it.copy(emailSent = false) }
    }
    
    fun clearError() {
        _uiState.update { it.copy(error = null) }
    }
}

